# Generated by Django 3.2 on 2022-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=123, max_length=150, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
