# Generated by Django 3.2 on 2022-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='web',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='web',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Teléfono'),
        ),
    ]
