# Generated by Django 3.2 on 2022-08-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
