# Generated by Django 3.2 on 2022-08-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('informacion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipo')),
            ],
        ),
    ]
