# Generated by Django 3.2 on 2022-08-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(upload_to='equipo'),
        ),
    ]
